steps:

- name: node:16
  # entrypoint: npm
  # args: ['--version']

# - name: node:16
#   entrypoint: npm
#   args: ['install']

# - name: node:16
#   entrypoint: npm
#   args: ['run','build']

# - name: 'docker'
#   args: ['build','-t','gcr.io/astral-host-350611/roteiros:latest','-t','gcr.io/astral-host-350611/roteiros:$SHORT_SHA','.']

