steps:
- name: 'docker'
  # args: ['build','-t','gcr.io/astral-host-350611/roteiros:latest','.']
  args: ['ls']

# - name: 'docker'
#   args: ['build','-t','gcr.io/astral-host-350611/roteiros:$SHORT_SHA','.']

# - name: 'docker'
#   args: ['run','d','--name','roteiro','gcr.io/astral-host-350611/roteiros:latest']

# - name: 'docker'
#   args: ['exec','roteiro','npm','test']

# - name: 'docker'
#   args: ['push','gcr.io/astral-host-350611/roteiros:latest']

# - name: 'docker'
#   args: ['push','gcr.io/astral-host-350611/roteiros:$SHORT_SHA']